### PR TITLE
Added Intel IPP optional support for LZ4 compression; Added `HDF5PLUGIN_INTEL_IPP_DIR` configuration environment variable

### LINKED ISSUE #144: LZ4 from Intel's ipp ?
For the bitshuffle (LZ4) filter (on Intel) it seems the Intel IPP decompressor can be faster than the LZ4 which is currently bundled. 

The licensing situation is not entirely clear to me but I think Intel makes this code available as a binary blob in oneapi and also on [pypi ](https://pypi.org/project/ipp/). From https://software.intel.com/content/www/us/en/develop/articles/oneapi-commercial-faq.html : it says "Yes, all of the oneAPI Toolkits are available for free download and use for commercial and non-commercial purposes". Blosc also has an option to build against IPP, so presumably it is possible.

One option might be to build against a special LZ4 rather than the one which is bundled. There is a recipe from Intel for building a patched LZ4 library which calls their versions instead, from:  $(intel)/oneapi/ipp/latest/components/components/interfaces/ipp_lz4/readme.html
``` 
$ unzip lz4-1.9.3.zip
$ cd lz4-1.9.3
$ patch -p1 < ../lz4-1.9.3.patch.bin
```

Another method would be to send the calls to `LZ4_decompress_fast` and `LZ4_decompress_safe` to `DecodeLZ4` from ipp. This means locating the include+lib folders for ipp when compiling. Doing something like this in setup.py :
`extra_objects = [ 'path_to/libippdc.a', 'path_to/libippcore.a' ]` 
does not appear to introduce a new runtime dependency.

Before going much further into this I guess you want to see a benchmark to find out if it makes any difference and check it does not makes things worse for amd, etc ? Or maybe the binary blob already creates other problems ?

### PR DESCRIPTION
**Pull request by t20100**
~~Merge PR #251 first!~~

This PR adds optional support of Intel IPP libraries for:
- The LZ4 compression library: Using the patch provided with IPP.
- Replacement of LZ4 calls in c-blosc2 (through `HAVE_IPP` macro)

It adds a `HDF5PLUGIN_IPP_DIR` env. var. to configure IPP root dir.

closes #144

### CODE REVIEW

**Comment by t20100** [comment]
I so far didn't managed to make a working filter with static linking of the ipp libs, but dynamic linking works (`LD_LIBRARY_PATH` needs to be set).

Only tested on Linux/gcc.

**Comment by t20100** [comment]
attn @jonwright

**Comment by jonwright** [comment]
Thanks! I will try to have a look. Static linking was working here with direct calls to ipp (not via the patched lz4):
https://github.com/jonwright/bslz4decoders/blob/main/bslz4decoders/ccodes/setup.py

**Comment by t20100** [comment]
This looks to work on all 3 platforms: macos, linux and windows

**Comment by jonwright** [comment]
I had a quick look. It seems I need to mess about with `LD_PRELOAD` to pick up libippdc.so and libipps.so before it runs. Not sure why for now, but I guess it is not static linking?

**Comment by t20100** [comment]
No, from what I tested static linking doesn't work with the latest version of IPP.

Actually, you can static link to the architecture specific versions of the functions but not to the so called 'dispatcher' that detects the architecture and calls the appropriate implementation which doesn't seems to be included in the static lib.

Instead of `LD_PRELOAD`, you can set `LD_LIBRARY_PATH`, which is what the `env/vars.sh` script provided with IPP does.

**Comment by vasole** [comment]
I'm curious. Any benchmarks performed?

**Comment by t20100** [comment]
Not yet

**Comment by t20100** [comment]
Fixed conflict

**Comment by t20100** [comment]
Thanks for the benchmark!

**Comment by t20100** [comment]
I also need to do `LD_PRELOAD` on some machine, which is not supposed to be needed.

**Comment by jonwright** [comment]
Looking at the numbers below, I remembered there are some other optimisations left (after IPP is available). It would be good to get these upstreamed too.

The difference of h5py_chunks vs hdf5_chunks = uses an existing memory buffer rather than a new allocation.

The omp routines are alternative (lock free) threading strategies. Either one or all threads reads offsets, but no sharing offset data between threads.

from https://github.com/jonwright/bslz4decoders/blob/main/bslz4decoders/test/test_bench_read.py

```
(py39_h5bench_no_ipp) hpc5-1103:/data/id11/jon/bslz4decoders/bslz4decoders/test % OMP_NUM_THREADS=20 taskset --cpu-list 0-40:2 python3 test_bench_read.py /data/id11/nanoscope/blc12454/id11/WAu5um/WAu5um_DT3/scan0001/eiger_0000.h5 /entry_0000/ESRF-ID11/eiger/data
h5py_chunks|decompress_bitshuffle 0 8942.0 MB, 2902.650 ms, 3080.6 MB/s
h5py_chunks|decompress_bitshuffle 1 8942.0 MB, 2886.047 ms, 3098.4 MB/s
h5py_chunks|decompress_bitshuffle 2 8942.0 MB, 2886.627 ms, 3097.7 MB/s
h5py_chunks|decompress_onecore 0 8942.0 MB, 4587.151 ms, 1949.4 MB/s
h5py_chunks|decompress_onecore 1 8942.0 MB, 4580.877 ms, 1952.0 MB/s
h5py_chunks|decompress_onecore 2 8942.0 MB, 4605.852 ms, 1941.5 MB/s
h5py_chunks|decompress_ipponecore 0 8942.0 MB, 4524.347 ms, 1976.4 MB/s
h5py_chunks|decompress_ipponecore 1 8942.0 MB, 4643.388 ms, 1925.8 MB/s
h5py_chunks|decompress_ipponecore 2 8942.0 MB, 4639.450 ms, 1927.4 MB/s
h5py_chunks|decompress_omp 0 8942.0 MB, 417.703 ms, 21407.6 MB/s
h5py_chunks|decompress_omp 1 8942.0 MB, 417.058 ms, 21440.7 MB/s
h5py_chunks|decompress_omp 2 8942.0 MB, 416.854 ms, 21451.2 MB/s
h5py_chunks|decompress_ippomp 0 8942.0 MB, 415.236 ms, 21534.8 MB/s
h5py_chunks|decompress_ippomp 1 8942.0 MB, 413.264 ms, 21637.6 MB/s
h5py_chunks|decompress_ippomp 2 8942.0 MB, 413.447 ms, 21628.0 MB/s
h5py_chunks|decompress_omp_blocks 0 8942.0 MB, 414.247 ms, 21586.2 MB/s
h5py_chunks|decompress_omp_blocks 1 8942.0 MB, 415.072 ms, 21543.3 MB/s
h5py_chunks|decompress_omp_blocks 2 8942.0 MB, 417.304 ms, 21428.1 MB/s
h5py_chunks|decompress_ippomp_blocks 0 8942.0 MB, 414.645 ms, 21565.5 MB/s
h5py_chunks|decompress_ippomp_blocks 1 8942.0 MB, 412.466 ms, 21679.4 MB/s
h5py_chunks|decompress_ippomp_blocks 2 8942.0 MB, 413.540 ms, 21623.2 MB/s
hdf5_chunks|decompress_bitshuffle 0 8942.0 MB, 2844.896 ms, 3143.2 MB/s
hdf5_chunks|decompress_bitshuffle 1 8942.0 MB, 2835.112 ms, 3154.0 MB/s
hdf5_chunks|decompress_bitshuffle 2 8942.0 MB, 2830.191 ms, 3159.5 MB/s
hdf5_chunks|decompress_onecore 0 8942.0 MB, 4654.629 ms, 1921.1 MB/s
hdf5_chunks|decompress_onecore 1 8942.0 MB, 4560.722 ms, 1960.7 MB/s
hdf5_chunks|decompress_onecore 2 8942.0 MB, 4541.947 ms, 1968.8 MB/s
hdf5_chunks|decompress_ipponecore 0 8942.0 MB, 4472.829 ms, 1999.2 MB/s
hdf5_chunks|decompress_ipponecore 1 8942.0 MB, 4482.431 ms, 1994.9 MB/s
hdf5_chunks|decompress_ipponecore 2 8942.0 MB, 4476.184 ms, 1997.7 MB/s
hdf5_chunks|decompress_omp 0 8942.0 MB, 376.589 ms, 23744.8 MB/s
hdf5_chunks|decompress_omp 1 8942.0 MB, 375.904 ms, 23788.1 MB/s
hdf5_chunks|decompress_omp 2 8942.0 MB, 375.802 ms, 23794.5 MB/s
hdf5_chunks|decompress_ippomp 0 8942.0 MB, 371.908 ms, 24043.7 MB/s
hdf5_chunks|decompress_ippomp 1 8942.0 MB, 370.702 ms, 24121.9 MB/s
hdf5_chunks|decompress_ippomp 2 8942.0 MB, 373.037 ms, 23970.9 MB/s
hdf5_chunks|decompress_omp_blocks 0 8942.0 MB, 379.385 ms, 23569.8 MB/s
hdf5_chunks|decompress_omp_blocks 1 8942.0 MB, 380.351 ms, 23510.0 MB/s
hdf5_chunks|decompress_omp_blocks 2 8942.0 MB, 382.101 ms, 23402.2 MB/s
hdf5_chunks|decompress_ippomp_blocks 0 8942.0 MB, 376.942 ms, 23722.5 MB/s
hdf5_chunks|decompress_ippomp_blocks 1 8942.0 MB, 378.489 ms, 23625.6 MB/s
hdf5_chunks|decompress_ippomp_blocks 2 8942.0 MB, 379.657 ms, 23552.9 MB/s
read_simple 0 8942.0 MB, 6774.031 ms, 1320.0 MB/s
read_simple 1 8942.0 MB, 6983.152 ms, 1280.5 MB/s
read_simple 2 8942.0 MB, 6974.647 ms, 1282.1 MB/s
read_direct 0 8942.0 MB, 3325.481 ms, 2688.9 MB/s
read_direct 1 8942.0 MB, 3072.226 ms, 2910.6 MB/s
read_direct 2 8942.0 MB, 3205.507 ms, 2789.6 MB/s

(py39_h5bench_no_ipp) hpc5-1103:/data/id11/jon/bslz4decoders/bslz4decoders/test % OMP_NUM_THREADS=2 taskset --cpu-list 0-2:2 python3 test_bench_read.py /data/id11/nanoscope/blc12454/id11/WAu5um/WAu5um_DT3/scan0001/eiger_0000.h5 /entry_0000/ESRF-ID11/eiger/datah5py_chunks|decompress_bitshuffle 0 8942.0 MB, 3462.142 ms, 2582.8 MB/s
h5py_chunks|decompress_bitshuffle 1 8942.0 MB, 3510.484 ms, 2547.2 MB/s
h5py_chunks|decompress_bitshuffle 2 8942.0 MB, 3525.621 ms, 2536.3 MB/s
h5py_chunks|decompress_onecore 0 8942.0 MB, 4573.907 ms, 1955.0 MB/s
h5py_chunks|decompress_onecore 1 8942.0 MB, 4593.928 ms, 1946.5 MB/s
h5py_chunks|decompress_onecore 2 8942.0 MB, 4625.164 ms, 1933.3 MB/s
h5py_chunks|decompress_ipponecore 0 8942.0 MB, 4538.345 ms, 1970.3 MB/s
h5py_chunks|decompress_ipponecore 1 8942.0 MB, 4534.538 ms, 1972.0 MB/s
h5py_chunks|decompress_ipponecore 2 8942.0 MB, 4549.373 ms, 1965.6 MB/s
h5py_chunks|decompress_omp 0 8942.0 MB, 2441.126 ms, 3663.1 MB/s
h5py_chunks|decompress_omp 1 8942.0 MB, 2433.551 ms, 3674.5 MB/s
h5py_chunks|decompress_omp 2 8942.0 MB, 2435.779 ms, 3671.1 MB/s
h5py_chunks|decompress_ippomp 0 8942.0 MB, 2396.292 ms, 3731.6 MB/s
h5py_chunks|decompress_ippomp 1 8942.0 MB, 2395.265 ms, 3733.2 MB/s
h5py_chunks|decompress_ippomp 2 8942.0 MB, 2402.814 ms, 3721.5 MB/s
h5py_chunks|decompress_omp_blocks 0 8942.0 MB, 2396.093 ms, 3731.9 MB/s
h5py_chunks|decompress_omp_blocks 1 8942.0 MB, 2422.886 ms, 3690.7 MB/s
h5py_chunks|decompress_omp_blocks 2 8942.0 MB, 2395.752 ms, 3732.5 MB/s
h5py_chunks|decompress_ippomp_blocks 0 8942.0 MB, 2374.297 ms, 3766.2 MB/s
h5py_chunks|decompress_ippomp_blocks 1 8942.0 MB, 2381.286 ms, 3755.1 MB/s
h5py_chunks|decompress_ippomp_blocks 2 8942.0 MB, 2376.047 ms, 3763.4 MB/s
hdf5_chunks|decompress_bitshuffle 0 8942.0 MB, 3427.586 ms, 2608.8 MB/s
hdf5_chunks|decompress_bitshuffle 1 8942.0 MB, 3417.624 ms, 2616.4 MB/s
hdf5_chunks|decompress_bitshuffle 2 8942.0 MB, 3407.377 ms, 2624.3 MB/s
hdf5_chunks|decompress_onecore 0 8942.0 MB, 4603.771 ms, 1942.3 MB/s
hdf5_chunks|decompress_onecore 1 8942.0 MB, 4580.245 ms, 1952.3 MB/s
hdf5_chunks|decompress_onecore 2 8942.0 MB, 4543.431 ms, 1968.1 MB/s
hdf5_chunks|decompress_ipponecore 0 8942.0 MB, 4542.036 ms, 1968.7 MB/s
hdf5_chunks|decompress_ipponecore 1 8942.0 MB, 4509.366 ms, 1983.0 MB/s
hdf5_chunks|decompress_ipponecore 2 8942.0 MB, 4493.616 ms, 1989.9 MB/s
hdf5_chunks|decompress_omp 0 8942.0 MB, 2406.341 ms, 3716.0 MB/s
hdf5_chunks|decompress_omp 1 8942.0 MB, 2395.954 ms, 3732.1 MB/s
hdf5_chunks|decompress_omp 2 8942.0 MB, 2402.482 ms, 3722.0 MB/s
hdf5_chunks|decompress_ippomp 0 8942.0 MB, 2352.962 ms, 3800.3 MB/s
hdf5_chunks|decompress_ippomp 1 8942.0 MB, 2354.750 ms, 3797.4 MB/s
hdf5_chunks|decompress_ippomp 2 8942.0 MB, 2404.504 ms, 3718.9 MB/s
hdf5_chunks|decompress_omp_blocks 0 8942.0 MB, 2409.483 ms, 3711.2 MB/s
hdf5_chunks|decompress_omp_blocks 1 8942.0 MB, 2368.860 ms, 3774.8 MB/s
hdf5_chunks|decompress_omp_blocks 2 8942.0 MB, 2362.159 ms, 3785.5 MB/s
hdf5_chunks|decompress_ippomp_blocks 0 8942.0 MB, 2417.654 ms, 3698.6 MB/s
hdf5_chunks|decompress_ippomp_blocks 1 8942.0 MB, 2344.883 ms, 3813.4 MB/s
hdf5_chunks|decompress_ippomp_blocks 2 8942.0 MB, 2343.214 ms, 3816.1 MB/s
read_simple 0 8942.0 MB, 6930.351 ms, 1290.3 MB/s
read_simple 1 8942.0 MB, 7133.187 ms, 1253.6 MB/s
read_simple 2 8942.0 MB, 7108.666 ms, 1257.9 MB/s
read_direct 0 8942.0 MB, 3574.357 ms, 2501.7 MB/s
read_direct 1 8942.0 MB, 3556.520 ms, 2514.3 MB/s
read_direct 2 8942.0 MB, 3563.554 ms, 2509.3 MB/s
```

**Pull request merged**
