### PR TITLE
Add options to use SSE2 and AVX2 (for bitshuffle and blosc)

### LINKED ISSUE #23: blosc filter sse2/avx2 support
As it is, sse2/avx is not taken into account while compiling the HDF5 blosc filter.

### PR DESCRIPTION
**Pull request by t20100**
This PR adds `--sse2` and `--avx2` build options to enable/disable SIMD instructions for blosc and bitshuffle.

closes #23

TODOS:

- [x] Test on Windows
- [x] Test on macOS

### CODE REVIEW

**Comment by t20100** [comment]
Not as simple as expected... Enabling AVX2 seems to cause some troubles.

**Comment by t20100** [comment]
Ready for review.

The idea is that:
- wheels are built for "generic CPU" with SSE2 support (as it is part of the x86_64 architecture)  and without AVX2.
- When building from source, by default, it is built:
  * For 'native' CPU on Linux (using all the capabilities of the building CPU at the expense of compatibility)
  * With SSE2 and AVX2 if those are available: there is some checks of compile options availability and CPU capabilities.

The `setup.py build` target have 3 options `native`, `sse2` and `avx2` which allow to control the compilation with a finer grain (those are used to generate the wheels, `build --openmp=False --native=False --sse2=True --avx2=False`).

**Comment by t20100** [comment]
BTW, this PR adds `cpuinfo` (https://pypi.org/project/py-cpuinfo/) to `setup_requires` in order to probe for SSE2 and AVX2 CPU capabilities from Python (so not needed when installing wheels).

**Comment by kif** [comment]
I tried to compile avx2 code on a computer lacking it (AVX1 is present: sandy-bridge)
python3 setup.py build --avx2=True --openmp=True
the bitshuffle binary uses ymm register, not the blosc one.

**Comment by vasole** [comment]
I would prefer not to have additional dependencies.

**Comment by t20100** [comment]
I'm fine with an extra pure-python build dependency, especially that now `setuptools` handles that...
but we can add a copy of `cpuinfo` in the root directory (it's a single file), this is how `python-blosc` is handling it... then we'll have to maintain the copy up-to-date.

**Comment by t20100** [comment]
Added local copy of `cpuinfo` to avoid build dependency.
Also update `MANIFEST.in` (related to #55)

**Comment by vasole** [comment]
Everything is fine except that I would aim at native=False, sse2=True and avx=False as defaults for a good compromise between performance and portability.

I think we need at least the opinion of @kif here.

@tschoonj what is the conda policy concerning SSE2 and AVX2?

**Comment by tschoonj** [comment]
The conda-forge default is to compile on Linux with:

```bash
CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe
```

The gcc [docs](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html) appear to suggest that this means that SSE2 would be available, but not AVX2...

I haven't checked for macOS and Windows, but I assume it will be similar.

**Comment by vasole** [comment]
@tschoonj 

Please, use the options native=False sse2=True avx2=False when building the conda packages for next release.

**Pull request merged**
