### PR TITLE
Added ehug2023 presentation and companion material

### LINKED ISSUE #183: Provide the notebook to run the "benchmark" used in the presentations

### PR DESCRIPTION
**Pull request by t20100**
This PR adds the presentation and benchmark script/notebook for the eHUG2023

closes #183

### CODE REVIEW

**Comment by t20100** [comment]
Added link to the video

**Comment by vasole** [comment]
I find confusing the slide below. Zfp is included in hdf5plugin but probably you meant something else.

image

**Comment by t20100** [comment]
> Zfp is included in hdf5plugin but probably you meant something else (Blosc2)

Yes, this slide compares the pre-filter+compressions available with the other filters available in `hdf5plugin` with what is provided by `blosc`/`blosc2`.
`ZFP` is available in hdf5plugin` and it is mentioned when going through the list of filters.
`ZFP` is also available as an extension of `blosc2` which is not yet available in `hdf5plugin` but should be. It needs time to work on it.

**Comment by t20100** [comment]
Typo fixed!

**Comment by t20100** [comment]
I also removed the `(not included yet in hdf5plugin)`, this is indeed missleading

**Pull request merged**
