### PR TITLE
Prepare 2.2 release

### PR DESCRIPTION
**Pull request by t20100**
This PR prepares a v2.2 release: update changelog + bump version

### CODE REVIEW

**Comment by vasole** [comment]
LGTM. Do you want a merge prior to the release of you intend to release from this branch?

**Comment by kif** [comment]
LGTM too

**Comment by t20100** [comment]
@vasole it's simpler to cut the release if it is merged, I can tag from github.

**Comment by vasole** [comment]
Yes, that is the approach I usually take. I asked because it is not the approach taken with silx.

**Comment by t20100** [comment]
I feel what we do in silx would be overkill here, so I take the simpler approach.

**Pull request merged**
