### PR TITLE
replace -openmp with -fopenmp

### PR DESCRIPTION
**Pull request by kif**
it changed the meaning of the option !

### CODE REVIEW

**Comment by vasole** [comment]
- get_platform failing in all the tests irrespective of Python 2 or Python 3
- the tests are passing on travis python 3.6 despite having the same error as in the other platforms

**Comment by vasole** [comment]
@t20100 

Why not to use distutils.util.get_platform?

**Comment by t20100** [comment]
@kif, nice catch!

@vasole,  I'm using the same `get_platform` as `bdist_wheel` is using as it inherits from it. This is to avoid building wheels for each version of python, but there is maybe other ways.

**Comment by vasole** [comment]
Well, something must be different because it got broken when using wheel but not when using distutils.util

**Pull request merged**
