### PR TITLE
Updated "zfp" filter to HZ5-ZFP v1.1.0 and ZFP v1.0.0

### PR DESCRIPTION
**Pull request by t20100**
This PR:
- Updates the subtree of `H5Z-ZFP` and `zfp` update to latest available versions.
- Adds a missing HDF5 variable to `hdf5_dl.c`
- Updates the documentation of embedded versions

### CODE REVIEW

**Comment by vasole** [comment]
image

**Comment by vasole** [comment]
Pull request issued at the source. https://github.com/LLNL/H5Z-ZFP/pull/93

**Review by vasole — APPROVED** [review]

**Comment by vasole** [comment]
Like with `bitshuffle`, I would merge with our changes.

**Comment by t20100** [comment]
I think we can wait a few days to see if https://github.com/LLNL/H5Z-ZFP/pull/93 goes through.

**Comment by t20100** [comment]
I updated the subtree of `H5Z-ZFP` to integrate https://github.com/LLNL/H5Z-ZFP/pull/93
It's ready for me.

**Pull request merged**
