### PR TITLE
Added BZip2 compression filter

### PR DESCRIPTION
**Pull request by t20100**
This PR adds the BZip2 compression filter from `PyTables` to `hdf5plugin`.
It also updates slightly the contribution documentation.

I didn't use `git subtree` for PyTables, instead I copy-pasted the 3 relevant files while keeping the same folder structure. As we add filters, we're also adding a lot of useless files, so maybe time to change the strategy of embedding everything, what do you think of this?

I'm also missing a hdf5 file with bzip2 compression that was produced by another tool.

Related to #110

### CODE REVIEW

**Comment by t20100** [comment]
Let's keep this as a Draft PR for now, and wait for an effective need to add it to `hdf5plugin`.

**Comment by vasole** [comment]
For easy-to-handle filters I do not mind to add them to the code repository. If PyTables uses it, I would add it.

**Comment by t20100** [comment]
OK, up to you then!
My feeling was that we'll have to maintain a filter that we are not sure is used, but as you say it's a simple one.

**Comment by t20100** [comment]
OK, up to you then!
My feeling was that we'll have to maintain a filter that we are not sure is used, but as you say it's a simple one.

**Pull request merged**
